INSTAGRAM_URL = 'https://www.instagram.com/'
INSTAGRAM_USER_INFO_URL_DEFAULT = 'https://www.instagram.com/{}/?__a=1'
INSTAGRAM_USER_INFO_URL_MOBILE = 'https://i.instagram.com/api/v1/users/{}/info/'
INSTAGRAM_EXPLORE_URL = 'https://www.instagram.com/explore/tags/{}/'

CHROMEDRIVER = 'chromedriver'
LOG_FILE = 'igscraper.log'
CHROMEDRIVER_LOG_FILE = 'chromedriver.log'
LOCAL_DB = 'igscraper.db'
USERS_DIR = 'users'
TAGS_DIR = 'tags'
TAG_TYPE_TOP = 'top'
TAG_TYPE_RECENT = 'recent'

# CSS & ID
USERNAME_CSS = '._7UhW9.fKFbl.yUEEX.KV-D4.fDxYl'
POSTS_CSS = '.v1Nh3.kIKUG._bz0w'
PAGE_USERNAME = '.sqdOP.yWX7d._8A5w5.ZIAjV'
DISPLAY_PIC_PUBLIC_CSS = '._6q-tv'
DISPLAY_PIC_PRIVATE_CSS = '.be6sR'
CREDENTIALS_BOXES_CSS = '._2hvTZ.pexuQ.zyHYP'
POST_PROFILE_NAME_CSS = '.e1e1d'
LOGIN_BOX_CSS = '.HmktE'
SECURITY_INPUT_BOX_CSS = '._2hvTZ.pexuQ.zyHYP'
SECURITY_BOX_BUTTON = '.sqdOP.L3NKy.y3zKF'
LOGIN_BUTTON_CSS = '.sqdOP.L3NKy.y3zKF'
SETTINGS_BUTTONS_CSS = '.aOOlW.HoLwm'
SUCCESS_LOGIN_USERNAME_CSS = '._7UhW9.fKFbl.yUEEX.KV-D4.fDxYl'
FAILED_LOGIN_MESSAGE_CSS = '.eiCW-'
USER_PRIVATE_CSS = '.rkEop'
SHOW_MORE_POSTS_CSS = '._7UhW9.xLCgt.qyrsm.h_zdq.uL8Hv.l4b0S'
NO_NOTIFICATIONS_BUTTON_CSS = '.aOOlW.HoLwm'
BUTTON_NO_SAVE_LOGIN_INFO_CSS = '.sqdOP.yWX7d.y3zKF'
IMG_CSS = '.FFVAD'
VID_CSS = '.tWeCl'
STORIES_DP_CSS = '.RR-M-.h5uC0'
STORIES_BAR_CSS = '._7zQEa'
STORIES_TAP_CSS = '._7UhW9.xLCgt.MMzan.h_zdq.uL8Hv'
STORIES_IMG_CSS = '.y-yJ5  '
STORIES_VID_CSS = '.y-yJ5.OFkrO'
STORIES_NEXT_CSS = '.ow3u_'
INDICATOR = '.Yi5aA'
NEXT_CONTROL_CSS = '.coreSpriteRightChevron'
MULTIPLE_CONTENT_UL_CSS = '.vi798'
MULTIPLE_CONTENT_LI_CSS = '.Ckrof'
SETTINGS_CSS = '._8-yf5'
POSTS_AMOUNT_CSS = '.g47SY '
POST_TIME_CSS = '._1o9PC.Nzb55'
SCROLL_LOAD_CSS = '.Igw0E.IwRSH.YBx95._4EzTm._9qQ0O.ZUqME'
ACCEPT_COOKIES_CSS = '.aOOlW.bIiDR'
CHROME_RELOAD_BUTTON_ID = 'reload-button'
SORRY_ID = 'sorry'

# XPATH
TOP_TAGS_XPATH = '/html/body/div[1]/section/main/article/div[1]/div/div'
RECENT_TAGS_XPATH = '/html/body/div[1]/section/main/article/div[2]/div'
