INSTAGRAM_URL = 'https://www.instagram.com/'

CHROMEDRIVER = 'chromedriver'
WEBDRIVERS = [CHROMEDRIVER]

CHROMEDRIVER_VERSION = 'v85.0.4183.87'
CHROMEDRIVER_LINUX_URL = 'https://chromedriver.storage.googleapis.com/85.0.4183.87/chromedriver_linux64.zip'
CHROMEDRIVER_WINDOWS_URL = 'https://chromedriver.storage.googleapis.com/85.0.4183.87/chromedriver_win32.zip'
CHROMEDRIVER_MACOS_URL = 'https://chromedriver.storage.googleapis.com/85.0.4183.87/chromedriver_mac64.zip'

LOG_FILE = 'igscraper.log'
CHROMEDRIVER_LOG_FILE = 'chromedriver.log'
WEBDRIVER_DIR = 'webdriver'
LOCAL_DB = 'igscraper.db'
USERS_DIR = 'users'
TAGS_DIR = 'tags'

TAG_TYPE_TOP = 'top'
TAG_TYPE_RECENT = 'recent'

# CSS & ID
USERNAME_CSS = '._7UhW9.fKFbl.yUEEX.KV-D4.fDxYl'
POSTS_CSS = '.v1Nh3.kIKUG._bz0w'
PAGE_NOT_AVAILABLE_PRIVATE_CSS = ('.error-container.-cx-PRIVATE-ErrorPage__errorContainer.'
                                  '-cx-PRIVATE-ErrorPage__errorContainer__')
PAGE_NOT_AVAILABLE_PUBLIC_CSS = '.MCXLF'
DISPLAY_PIC_PUBLIC_CSS = '._6q-tv'
DISPLAY_PIC_PRIVATE_CSS = '.be6sR'
CREDENTIALS_CSS = '._2hvTZ.pexuQ.zyHYP'
POST_PROFILE_NAME_CSS = '.e1e1d'
LOGIN_BOX_CSS = '.HmktE'
SECURITY_INPUT_BOX_CSS = '._2hvTZ.pexuQ.zyHYP'
SECURITY_BOX_BUTTON = '.sqdOP.L3NKy.y3zKF'
LOGIN_BUTTON_CSS = '.sqdOP.L3NKy.y3zKF'
SETTINGS_BUTTONS_CSS = '.aOOlW.HoLwm'
SUCCESS_LOGIN_USERNAME_CSS = '._7UhW9.fKFbl.yUEEX.KV-D4.fDxYl'
FAILED_LOGIN_MESSAGE_CSS = '.eiCW-'
USER_PRIVATE_CSS = '.rkEop'
SHOW_MORE_POSTS_CSS = '._7UhW9.xLCgt.qyrsm.h_zdq.uL8Hv.l4b0S'
NO_NOTIFICATIONS_BUTTON_CSS = '.aOOlW.HoLwm'
NOT_SAVE_LOGIN_INFO_BUTTON_CSS = '.sqdOP.yWX7d.y3zKF'
IMG_CSS = '.FFVAD'
VID_CSS = '.tWeCl'
STORIES_DP_CSS = '.RR-M-.h5uC0'
STORIES_BAR_CSS = '._7zQEa'
STORIES_TAP_CSS = '._7UhW9.xLCgt.MMzan.h_zdq.uL8Hv'
STORIES_IMG_CSS = '.y-yJ5  '
STORIES_VID_CSS = '.y-yJ5.OFkrO'
STORIES_NEXT_CSS = '.ow3u_'
INDICATOR = '.Yi5aA'
NEXT_CONTROL_CSS = '.coreSpriteRightChevron'
MULTIPLE_CONTENT_UL_CSS = '.vi798'
MULTIPLE_CONTENT_LI_CSS = '.Ckrof'
SETTINGS_CSS = '._8-yf5'
POSTS_AMOUNT_CSS = '.g47SY '
POST_TIME_CSS = '._1o9PC.Nzb55'
SCROLL_LOAD_CSS = '.Igw0E.IwRSH.YBx95._4EzTm._9qQ0O.ZUqME'
CHROME_RELOAD_BUTTON_ID = 'reload-button'
SORRY_ID = 'sorry'

# XPATH
TOP_TAGS_XPATH = '/html/body/div[1]/section/main/article/div[1]/div/div'
RECENT_TAGS_XPATH = '/html/body/div[1]/section/main/article/div[2]/div'
